import { REACT_APP_BACKEND_PORT, REACT_APP_FRONTEND_PORT, REACT_APP_IP } from '@env';

export const BACKEND_PORT = REACT_APP_BACKEND_PORT;
export const FRONTEND_PORT = REACT_APP_FRONTEND_PORT;
export const IP = REACT_APP_IP;

